name: openshot-qt CI Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    defaults:
      run:
        shell: bash
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo add-apt-repository ppa:openshot.developers/libopenshot-daily
        sudo apt update
        sudo apt install libopenshot-audio-dev libopenshot-dev \
                         python3-openshot \
                         python3-pyqt5 python3-pyqt5.qtsvg \
                         python3-pyqt5.qtwebengine python3-pyqt5.qtopengl \
                         python3-zmq python3-xdg \
                         qttranslations5-l10n libssl-dev libbabl-dev
        pip3 install setuptools wheel 
        pip3 install cx_Freeze==6.1 distro defusedxml requests certifi \
                     chardet urllib3 sentry-sdk 

    - name: Build Python package
      run: python3 freeze.py build

    - name: Test
      run: python3 ./src/tests/query_tests.py -platform minimal
